# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67cc6d4dbf40425a6942a28ee5df6425d094d35980ae3f0660efd3987a387f4519ae3ab0b4d3fc03853dbe08e7cf57e663ba5777a9a16075fd68b992f427b78b

test:
  secret_key_base: 9a0b2bdd5180b325e86bd6569146c44374c9f52dc6e4ba66aa20edfa03da3db74e20ca672ae7b6c84031409db8c1131590a48b8c578093701443bc73736dfe2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
